#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : opencl-clang
Version  : 70
Release  : 3
URL      : https://github.com/tripzero/opencl-clang/archive/ocl-open-70.tar.gz
Source0  : https://github.com/tripzero/opencl-clang/archive/ocl-open-70.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : NCSA
Requires: opencl-clang-lib = %{version}-%{release}
Requires: opencl-clang-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : git
BuildRequires : llvm
BuildRequires : llvm-dev

%description
[![Build Status](https://travis-ci.com/intel/opencl-clang.svg?branch=ocl-open-70)](https://travis-ci.com/intel/opencl-clang)

%package dev
Summary: dev components for the opencl-clang package.
Group: Development
Requires: opencl-clang-lib = %{version}-%{release}
Provides: opencl-clang-devel = %{version}-%{release}

%description dev
dev components for the opencl-clang package.


%package lib
Summary: lib components for the opencl-clang package.
Group: Libraries
Requires: opencl-clang-license = %{version}-%{release}

%description lib
lib components for the opencl-clang package.


%package license
Summary: license components for the opencl-clang package.
Group: Default

%description license
license components for the opencl-clang package.


%prep
%setup -q -n opencl-clang-ocl-open-70

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551898372
mkdir -p clr-build
pushd clr-build
%cmake .. -DPREFERRED_LLVM_VERSION="7.0.1"
make  %{?_smp_mflags} VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1551898372
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/opencl-clang
cp LICENSE %{buildroot}/usr/share/package-licenses/opencl-clang/LICENSE
pushd clr-build
%make_install
popd
## install_append content
ln -s %{buildroot}/usr/lib64/libcommon_clang.so.7 libopencl_clang.so.7
## install_append end

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/cclang/common_clang.h
/usr/lib64/libcommon_clang.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcommon_clang.so.7

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/opencl-clang/LICENSE
