#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : opencl-clang
Version  : 9.0.0
Release  : 12
URL      : https://github.com/intel/opencl-clang/archive/v9.0.0/opencl-clang-9.0.0.tar.gz
Source0  : https://github.com/intel/opencl-clang/archive/v9.0.0/opencl-clang-9.0.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : NCSA
Requires: opencl-clang-lib = %{version}-%{release}
Requires: opencl-clang-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : git
BuildRequires : llvm-dev
BuildRequires : llvm-extras

%description
[![Build Status](https://travis-ci.com/intel/opencl-clang.svg?branch=master)](https://travis-ci.com/intel/opencl-clang)

%package dev
Summary: dev components for the opencl-clang package.
Group: Development
Requires: opencl-clang-lib = %{version}-%{release}
Provides: opencl-clang-devel = %{version}-%{release}
Requires: opencl-clang = %{version}-%{release}

%description dev
dev components for the opencl-clang package.


%package lib
Summary: lib components for the opencl-clang package.
Group: Libraries
Requires: opencl-clang-license = %{version}-%{release}

%description lib
lib components for the opencl-clang package.


%package license
Summary: license components for the opencl-clang package.
Group: Default

%description license
license components for the opencl-clang package.


%prep
%setup -q -n opencl-clang-9.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1569979636
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. -DLLVM_LINK_LLVM_DYLIB=ON
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1569979636
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/opencl-clang
cp LICENSE %{buildroot}/usr/share/package-licenses/opencl-clang/LICENSE
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/cclang/common_clang.h
/usr/lib64/libopencl-clang.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libopencl-clang.so.9

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/opencl-clang/LICENSE
