#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : opencl-clang
Version  : 10.0.0.1
Release  : 15
URL      : https://github.com/intel/opencl-clang/archive/v10.0.0-1/opencl-clang-10.0.0.1.tar.gz
Source0  : https://github.com/intel/opencl-clang/archive/v10.0.0-1/opencl-clang-10.0.0.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : NCSA
Requires: opencl-clang-lib = %{version}-%{release}
Requires: opencl-clang-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : git
BuildRequires : llvm-dev
BuildRequires : llvm-extras
BuildRequires : llvm-staticdev
Patch1: 0001-Building-in-tree-with-LLVM-10.0-with-the-LLVM_LINK_L.patch

%description
[![Build Status](https://travis-ci.com/intel/opencl-clang.svg?branch=ocl-open-100)](https://travis-ci.com/intel/opencl-clang)

%package dev
Summary: dev components for the opencl-clang package.
Group: Development
Requires: opencl-clang-lib = %{version}-%{release}
Provides: opencl-clang-devel = %{version}-%{release}
Requires: opencl-clang = %{version}-%{release}

%description dev
dev components for the opencl-clang package.


%package lib
Summary: lib components for the opencl-clang package.
Group: Libraries
Requires: opencl-clang-license = %{version}-%{release}

%description lib
lib components for the opencl-clang package.


%package license
Summary: license components for the opencl-clang package.
Group: Default

%description license
license components for the opencl-clang package.


%prep
%setup -q -n opencl-clang-10.0.0-1
cd %{_builddir}/opencl-clang-10.0.0-1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1588377607
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. -DLLVM_LINK_LLVM_DYLIB=ON \
-DCLANG_LINK_CLANG_DYLIB=ON
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1588377607
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/opencl-clang
cp %{_builddir}/opencl-clang-10.0.0-1/LICENSE %{buildroot}/usr/share/package-licenses/opencl-clang/a57da614b8bbf59bc1c345bc79a611acee3b25d0
pushd clr-build
%make_install
popd
## install_append content
# igc wants this to be called opencl_clang
#ln -s libcommon_clang.so.7 %{buildroot}/usr/lib64/libopencl_clang.so.7
#ln -s libcommon_clang.so %{buildroot}/usr/lib64/libopencl_clang.so
## install_append end

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/cclang/common_clang.h
/usr/lib64/libopencl-clang.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libopencl-clang.so.10

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/opencl-clang/a57da614b8bbf59bc1c345bc79a611acee3b25d0
